### PR TITLE
Streaming methods now identical between monolith and micro generators

### PR DESCRIPTION
**Pull request by chrisdunelm**

### CODE REVIEW

**Comment by chrisdunelm** [comment]
Apologies that this PR is a little on the larger size.
However, much of it is just updates to the "golden" test files.

**Comment by jskeet** [comment]
I don't know if @amanda-tarafa is on vacation today - if she is, I'll look at this on Monday

**Comment by amanda-tarafa** [comment]
I'm here, on it :)

**Review by amanda-tarafa — APPROVED** [review]
LGTM

**Comment by chrisdunelm** [comment]
Thank you :)

**Pull request merged**
