### PR TITLE
chore: Add a prepend dot function and code refactor

### PR DESCRIPTION
**Pull request by Hectorhammett**
Add a static prependDot function to the Helper's class.
Code refactor to make use of the Helper's prependDot function.

### CODE REVIEW

**Review by noahdietz — APPROVED** [review]
It's perfect 🥲

**Comment by noahdietz** [comment]
I changed the title from `fix` to `chore` b.c this type of internal refactor need not create a release or show up in release notes

`fix` triggers a patch release, `chore` does not.

**Comment by noahdietz** [comment]
Oh and don't forget to reference the issue if available. Including `Fixes #427` in the PR description closes that bug on merge :)

**Comment by Hectorhammett** [comment]
> Oh and don't forget to reference the issue if available. Including `Fixes #427` in the PR description closes that bug on merge :)

Oh! Right! Will do!

**Pull request merged**
