### PR TITLE
chore(engx): Apply phpcsfixer lint fixes to src/ [ggphp]

### PR DESCRIPTION
**Pull request by miraleung**

### CODE REVIEW

**Comment by miraleung** [comment]
@chrisdunelm On my machine, this seems to be failing on master - could you please confirm if it needs addressing separately?

**Comment by chrisdunelm** [comment]
This failure is most likely because the googleapis sub-module is out of date. There was a fix that went into googleapis a day or two ago, which is required for cloudfunctions.

**Comment by chrisdunelm** [comment]
A few questions:
* Should `.php_cs.cache` be included in the repo? I suspect it should be in `.gitignore`.
* There's quite a few generated (by protobuf) files in `src/`; should these be excluded from auto-formatting?
* The `googleapis` submodule appears to have an update in this PR - this is likely linked to the CI failure.

**Comment by miraleung** [comment]
> A few questions:
> 
> * Should `.php_cs.cache` be included in the repo? I suspect it should be in `.gitignore`.
> * There's quite a few generated (by protobuf) files in `src/`; should these be excluded from auto-formatting?
> * The `googleapis` submodule appears to have an update in this PR - this is likely linked to the CI failure.

Done for items 1 and 3. For 2, it wasn't obvious from scanning `src/` which files are generated, would you know what those are?

**Comment by chrisdunelm** [comment]
The files in `src/Google`, `src/GPBMetadata`, and `src/Grpc` are all generated. It should be relatively simple to move these, perhaps into `src/generated`; `composer.json` will need updating, which I _think_ should all be mostly straighfoward.
It may be worth doing the move before this PR.

**Comment by chrisdunelm** [comment]
The `build_proto.sh` script in the root directory will need changing too, if you do choose to move these generated files.
(And there _may_ be something else that generates src files, but I can't recall it right now)

**Comment by miraleung** [comment]
> The files in `src/Google`, `src/GPBMetadata`, and `src/Grpc` are all generated. It should be relatively simple to move these, perhaps into `src/generated`; `composer.json` will need updating, which I _think_ should all be mostly straighfoward.
> It may be worth doing the move before this PR.

Thanks Chris, I've reverted those files for this PR. Will do the file move and updates before proceeding with auto-linting checks.

**Review by chrisdunelm — APPROVED** [review]
LGTM

**Pull request merged**
