### PR TITLE
feat: add manual fix for bc-breaking changes

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by noahdietz** [comment]
I think now the test is failing because of the tricky `autoload` functionality https://github.com/googleapis/gapic-generator-php/blob/main/tests/Unit/autoload.php that resolves proto messages and field values with dumbies.

**Comment by bshaffer** [comment]
@noahdietz any idea what the deal is with the failing bazel integration tests?

**Comment by noahdietz** [comment]
> @noahdietz any idea what the deal is with the failing bazel integration tests?

You'll need to run `bazel run tests/Integration:asset_update` (`logging_update` and `videointelligence_update`) to update those golden files since this change affects their generated code.

Sorry for all of the toil.

**Comment by bshaffer** [comment]
@noahdietz since we have the Integration tests already, which cover the same thing, should I just get rid of the tests i added to `tests/Unit`?

**Comment by noahdietz** [comment]
> @noahdietz since we have the Integration tests already, which cover the same thing, should I just get rid of the tests i added to `tests/Unit`?

Yeah, that is probably fine.

**Pull request merged**
