### PR TITLE
chore: Rename optionalArgs to callOptions

### PR DESCRIPTION
**Pull request by saranshdhingra**

### CODE REVIEW

**Comment by saranshdhingra** [comment]
So the bazel tests are passing locally, could it just be the cache in play?
Also, @noahdietz I didn't use the command before opening the PRs, what options do I have now?

**Comment by noahdietz** [comment]
> So the bazel tests are passing locally, could it just be the cache in play? Also, @noahdietz I didn't use the command before opening the PRs, what options do I have now?

Rotate the cache value, then rerun the GitHub Checks manually.

**Review by noahdietz — COMMENTED** [review]
LGTM but let's let @bshaffer review as well.

**Review by bshaffer — APPROVED** [review]
LGTM with one suggestion

**Pull request merged**
